output "control_plane_private_ips" {
  description = "Control plane private IPs from compute module."
  value       = module.talos-cp.control_plane_private_ips
}

output "talos_bootstrap_node" {
  description = "Control plane node selected for Talos bootstrap."
  value       = module.talos-bootstrap.bootstrap_node
}

output "talos_cluster_endpoint" {
  description = "Talos/Kubernetes endpoint used for machine configuration generation."
  value       = module.talos-bootstrap.cluster_endpoint
}

output "talosconfig" {
  description = "Talos client configuration generated by Terraform."
  value       = module.talos-bootstrap.talosconfig
  sensitive   = true
}

output "kubeconfig_raw" {
  description = "Kubeconfig generated by Terraform after bootstrap."
  value       = module.talos-bootstrap.kubeconfig_raw
  sensitive   = true
}
